.TH "Animation" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Animation\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBVec2Int\fP \fBtilePosition\fP"
.br
.ti -1c
.RI "int \fBcurrentFrame\fP"
.br
.ti -1c
.RI "int \fBframeCount\fP"
.br
.ti -1c
.RI "Uint32 \fBlastUpdateTime\fP"
.br
.ti -1c
.RI "double \fBanimationSpeed\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double animationSpeed"

.SS "int currentFrame"

.SS "int ENTITY_ID"

.SS "int frameCount"

.SS "Uint32 lastUpdateTime"

.SS "\fBVec2Int\fP tilePosition"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
