.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/Animation.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/Animation.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Animation\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAnimation_init\fP (\fBAnimation\fP *animations, int entity_ID, int *total_animationComponents, \fBVec2Int\fP tilePosition, int frameCount, double animationSpeed)"
.br
.ti -1c
.RI "void \fBAnimation_delete\fP (\fBAnimation\fP *animations, int entity_ID, int *total_animationComponents)"
.br
.ti -1c
.RI "void \fBAnimation_deserialise\fP (\fBAnimation\fP *animations, int *total_animationComponents, int maxNumberOfComponents, char path[255])"
.br
.ti -1c
.RI "void \fBAnimation_serialise\fP (\fBAnimation\fP *animations, int maxNumberOfComponents, char path[255])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Animation_delete (\fBAnimation\fP * animations, int entity_ID, int * total_animationComponents)"

.SS "void Animation_deserialise (\fBAnimation\fP * animations, int * total_animationComponents, int maxNumberOfComponents, char path[255])"

.SS "void Animation_init (\fBAnimation\fP * animations, int entity_ID, int * total_animationComponents, \fBVec2Int\fP tilePosition, int frameCount, double animationSpeed)"

.SS "void Animation_serialise (\fBAnimation\fP * animations, int maxNumberOfComponents, char path[255])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
