.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/AnimationSystems.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/AnimationSystems.c
.SH SYNOPSIS
.br
.PP
\fC#include 'AnimationSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAnimation_update\fP (\fBLayout\fP currentLayout, \fBAnimation\fP *animation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Animation_update (\fBLayout\fP currentLayout, \fBAnimation\fP * animation)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
