.TH "Camera" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ENTITY_ID"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
