.TH "Collider" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collider
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collider\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBCollider_colliderType\fP \fBtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ENTITY_ID"

.SS "\fBCollider_colliderType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
