.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/Collider.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/Collider.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Collider\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCollider_init\fP (\fBCollider\fP *colliders, int entityID, int *total_colliderComponents, bool isDynamic)"
.br
.ti -1c
.RI "void \fBCollider_delete\fP (\fBCollider\fP *colliders, int entityID, int *total_colliderComponents)"
.br
.ti -1c
.RI "void \fBCollider_deserialise\fP (\fBCollider\fP *colliders, int *total_colliderComponents, int maxNumberOfComponents, char path[255])"
.br
.ti -1c
.RI "void \fBCollider_serialise\fP (\fBCollider\fP *colliders, int maxNumberOfComponents, char path[255])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Collider_delete (\fBCollider\fP * colliders, int entityID, int * total_colliderComponents)"

.SS "void Collider_deserialise (\fBCollider\fP * colliders, int * total_colliderComponents, int maxNumberOfComponents, char path[255])"

.SS "void Collider_init (\fBCollider\fP * colliders, int entityID, int * total_colliderComponents, bool isDynamic)"

.SS "void Collider_serialise (\fBCollider\fP * colliders, int maxNumberOfComponents, char path[255])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
