.TH "CollisionBox" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollisionBox
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CollisionBox\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBVec2\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the size of the entity\&. This components is mainly, but not exclusively used for collision and click detection\&. 
.SH "Field Documentation"
.PP 
.SS "int ENTITY_ID"

.SS "\fBVec2\fP size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
