.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/ColliderSystems.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/ColliderSystems.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'ECS\&.h'\fP
.br
\fC#include 'CollisionBoxSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCollider_checkForCollision\fP (\fBLayout\fP *currentLayoutW, \fBCollider\fP *dynamicC, \fBCollider\fP *staticC, \fBVec2\fP *contactPoint, \fBVec2\fP *contactNormal, double *tHitNear, double deltaT)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool Collider_checkForCollision (\fBLayout\fP * currentLayoutW, \fBCollider\fP * dynamicC, \fBCollider\fP * staticC, \fBVec2\fP * contactPoint, \fBVec2\fP * contactNormal, double * tHitNear, double deltaT)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
