.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/Collider.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/Collider.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'Math\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCollider\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBCollider_colliderType\fP"
.br
.ti -1c
.RI "typedef struct \fBCollider\fP \fBCollider\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCollider_colliderType\fP { \fBSTATIC\fP = 0, \fBDYNAMIC\fP = 1 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBCollider\fP \fBCollider\fP"

.SS "typedef int \fBCollider_colliderType\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCollider_colliderType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTATIC \fP\fP
.TP
\fB\fIDYNAMIC \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
