.TH "Editor" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Editor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Editor\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "bool \fBisSelected\fP"
.br
.ti -1c
.RI "bool \fBcopied\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enables the user to edit entities\&. 
.SH "Field Documentation"
.PP 
.SS "bool copied"

.SS "int ENTITY_ID"

.SS "bool isSelected"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
