.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/EntityRenderer.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/EntityRenderer.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEntityRenderer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBRenderFilter\fP \fBRenderFilter\fP"
.br
.ti -1c
.RI "typedef struct \fBEntityRenderer\fP \fBEntityRenderer\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRenderFilter\fP { \fBRENDER_FILTER_ALLWAYS\fP = 0, \fBRENDER_FILTER_EDIT\fP = 1, \fBRENDER_FILTER_GAME\fP = 2 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBEntityRenderer\fP \fBEntityRenderer\fP"

.SS "typedef enum \fBRenderFilter\fP \fBRenderFilter\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRenderFilter\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRENDER_FILTER_ALLWAYS \fP\fP
.TP
\fB\fIRENDER_FILTER_EDIT \fP\fP
.TP
\fB\fIRENDER_FILTER_GAME \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
