.TH "GameTime" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameTime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBlastUpdateTime\fP"
.br
.ti -1c
.RI "long int \fBdeltaT\fP"
.br
.ti -1c
.RI "long int \fBtimeSinceStart\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long int deltaT"

.SS "long int lastUpdateTime"

.SS "long int timeSinceStart"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
