.TH "GameAppearance" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameAppearance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBisFullScrean\fP"
.br
.ti -1c
.RI "char \fBwindowName\fP [255]"
.br
.ti -1c
.RI "\fBVec2Int\fP \fBwindowDimensions\fP"
.br
.ti -1c
.RI "\fBRGBAColor\fP \fBbackgroundColor\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBRGBAColor\fP backgroundColor"

.SS "bool isFullScrean"

.SS "\fBVec2Int\fP windowDimensions"

.SS "char windowName[255]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
