.TH "Interactable" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interactable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Interactable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBInteractableType\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBnextInFocus\fP"
.br
.ti -1c
.RI "bool \fBhasFocus\fP"
.br
.ti -1c
.RI "bool \fBactiveInteractions\fP [\fBNUMBER_OF_INTERACTION_TYPES\fP]"
.br
.ti -1c
.RI "\fBInteraction\fP * \fBinteractionHead\fP"
.br
.ti -1c
.RI "\fBInteraction\fP * \fBlatestInteraction\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool activeInteractions[\fBNUMBER_OF_INTERACTION_TYPES\fP]"

.SS "int ENTITY_ID"

.SS "bool hasFocus"

.SS "\fBInteraction\fP* interactionHead"

.SS "\fBInteraction\fP* latestInteraction"

.SS "int nextInFocus"

.SS "\fBInteractableType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
