.TH "InteractionData_collision" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InteractionData_collision
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InteractableSystems\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBentityID\fP"
.br
.ti -1c
.RI "\fBVec2\fP \fBcollisionNormal\fP"
.br
.ti -1c
.RI "\fBGameState\fP * \fBgameState\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBVec2\fP collisionNormal"

.SS "int entityID"

.SS "\fBGameState\fP* gameState"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
