.TH "Interaction" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interaction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Interactable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBInteractionType\fP \fBtype\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "\fBInteractionType\fP \fBnextInteractionType\fP"
.br
.ti -1c
.RI "struct \fBInteraction\fP * \fBnextInteraction\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* data"

.SS "struct \fBInteraction\fP* nextInteraction"

.SS "\fBInteractionType\fP nextInteractionType"

.SS "\fBInteractionType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
