.TH "InteractionData_keydown" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InteractionData_keydown
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InteractableSystems\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBkey\fP"
.br
.ti -1c
.RI "Uint16 \fBmod\fP"
.br
.ti -1c
.RI "int \fBspecialKey\fP"
.br
.ti -1c
.RI "\fBLayout\fP ** \fBlayoutsPtr\fP"
.br
.ti -1c
.RI "int * \fBnumberOfLayoutsPtr\fP"
.br
.ti -1c
.RI "\fBGameResources\fP * \fBgameResourcesPtr\fP"
.br
.ti -1c
.RI "char * \fBplayerName\fP"
.br
.ti -1c
.RI "\fBLayout\fP ** \fBcurrentLayoutPtr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBLayout\fP** currentLayoutPtr"

.SS "\fBGameResources\fP* gameResourcesPtr"

.SS "char key"

.SS "\fBLayout\fP** layoutsPtr"

.SS "Uint16 mod"

.SS "int* numberOfLayoutsPtr"

.SS "char* playerName"

.SS "int specialKey"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
