.TH "LayoutMap" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayoutMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ECS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstart\fP"
.br
.RI "The index of the first element of the list of a certain type of components, which belongs to this layout\&. "
.ti -1c
.RI "int \fBend\fP"
.br
.RI "The index after the last element of the list of a certain type of components, which belongs to this layout\&. "
.in -1c
.SH "Field Documentation"
.PP 
.SS "int end"

.PP
The index after the last element of the list of a certain type of components, which belongs to this layout\&. 
.SS "int start"

.PP
The index of the first element of the list of a certain type of components, which belongs to this layout\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
