.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/main.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <SDL\&.h>\fP
.br
\fC#include <SDL_image\&.h>\fP
.br
\fC#include 'Game\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXSAMPLES\fP   500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXSAMPLES   500"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
