.TH "MovementController" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovementController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MovementController\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBMovementStyle\fP \fBmovementStyle\fP"
.br
.ti -1c
.RI "\fBVec2\fP \fBcollisionNormal\fP"
.br
.ti -1c
.RI "\fBVec2\fP \fBpreviousDirection\fP"
.br
.ti -1c
.RI "double \fBmaxSpeed\fP"
.br
.ti -1c
.RI "double \fBacceleration\fP"
.br
.ti -1c
.RI "double \fBdeceleration\fP"
.br
.ti -1c
.RI "double \fBmaxFallSpeed\fP"
.br
.ti -1c
.RI "double \fBgravity\fP"
.br
.ti -1c
.RI "double \fBjumpHeight\fP"
.br
.ti -1c
.RI "double \fBtimeToApex\fP"
.br
.ti -1c
.RI "bool \fBdoubleJump\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "double acceleration"

.SS "\fBVec2\fP collisionNormal"

.SS "double deceleration"

.SS "bool doubleJump"

.SS "int ENTITY_ID"

.SS "double gravity"

.SS "double jumpHeight"

.SS "double maxFallSpeed"

.SS "double maxSpeed"

.SS "\fBMovementStyle\fP movementStyle"

.SS "\fBVec2\fP previousDirection"

.SS "double timeToApex"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
