.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/MovementControllerSystems.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/MovementControllerSystems.c
.SH SYNOPSIS
.br
.PP
\fC#include 'MovementControllerSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMovementController_update\fP (\fBLayout\fP *currentLayout, \fBMovementController\fP *movementController, double delta_t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MovementController_update (\fBLayout\fP * currentLayout, \fBMovementController\fP * movementController, double delta_t)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
