.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/MovementController.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/MovementController.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'Math\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMovementController\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBMovementStyle\fP \fBMovementStyle\fP"
.br
.ti -1c
.RI "typedef struct \fBMovementController\fP \fBMovementController\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMovementStyle\fP { \fBPLATFORMER\fP = 0, \fBGOOMBA\fP = 1 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBMovementController\fP \fBMovementController\fP"

.SS "typedef enum \fBMovementStyle\fP \fBMovementStyle\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMovementStyle\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPLATFORMER \fP\fP
.TP
\fB\fIGOOMBA \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
