.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/PhysicsBody.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/PhysicsBody.c
.SH SYNOPSIS
.br
.PP
\fC#include 'PhysicsBody\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPhysicsBody_init\fP (\fBPhysicsBody\fP *physicsBodies, int entityID, int *total_physicsBodyComponents, double mass)"
.br
.ti -1c
.RI "void \fBPhysicsBody_delete\fP (\fBPhysicsBody\fP *physicsBodies, int entityID, int *total_physicsBodyComponents)"
.br
.ti -1c
.RI "void \fBPhysicsBody_deserialise\fP (\fBPhysicsBody\fP *physicsBodies, int *total_physicsBodyComponents, int maxNumberOfComponents, char path[255])"
.br
.ti -1c
.RI "void \fBPhysicsBody_serialise\fP (\fBPhysicsBody\fP *physicsBodies, int maxNumberOfComponents, char path[255])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PhysicsBody_delete (\fBPhysicsBody\fP * physicsBodies, int entityID, int * total_physicsBodyComponents)"

.SS "void PhysicsBody_deserialise (\fBPhysicsBody\fP * physicsBodies, int * total_physicsBodyComponents, int maxNumberOfComponents, char path[255])"

.SS "void PhysicsBody_init (\fBPhysicsBody\fP * physicsBodies, int entityID, int * total_physicsBodyComponents, double mass)"

.SS "void PhysicsBody_serialise (\fBPhysicsBody\fP * physicsBodies, int maxNumberOfComponents, char path[255])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
