.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/PhysicsBodySystems.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/PhysicsBodySystems.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ECS\&.h'\fP
.br
\fC#include 'PositionSystems\&.h'\fP
.br
\fC#include 'ColliderSystems\&.h'\fP
.br
\fC#include 'InteractableSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPhysicsBody_update\fP (\fBLayout\fP *currentLayout, \fBPhysicsBody\fP *physicsBody, double deltaT, \fBGameState\fP *gameState)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PhysicsBody_update (\fBLayout\fP * currentLayout, \fBPhysicsBody\fP * physicsBody, double deltaT, \fBGameState\fP * gameState)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
