.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/PositionSystems.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/PositionSystems.c
.SH SYNOPSIS
.br
.PP
\fC#include 'PositionSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPosition_moveBy\fP (\fBPosition\fP *position, \fBVec2\fP amount)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Position_moveBy (\fBPosition\fP * position, \fBVec2\fP amount)"
Moves entity by a given amount\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The position component who's value we want to change\&. 
.br
\fIamount\fP A 2d vector by which the component should be transformed\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
