.TH "Ray2" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ray2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CollisionBoxSystems\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBVec2\fP \fBorigin\fP"
.br
.RI "origin point of the ray\&. "
.ti -1c
.RI "\fBVec2\fP \fBdestination\fP"
.br
.RI "destination point of the ray\&. "
.in -1c
.SH "Detailed Description"
.PP 
This struct is used for collision detection\&. 
.SH "Field Documentation"
.PP 
.SS "\fBVec2\fP destination"

.PP
destination point of the ray\&. 
.SS "\fBVec2\fP origin"

.PP
origin point of the ray\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
