.TH "RenderProperties" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderProperties
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tilemap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBisVisible\fP"
.br
.RI "The component is only rendered when this is set to true\&. "
.ti -1c
.RI "double \fBopacity\fP"
.br
.RI "The opacity of an entity\&. "
.ti -1c
.RI "double \fBscale\fP"
.br
.RI "The scale of rendering\&. "
.in -1c
.SH "Detailed Description"
.PP 
Details of a component's rendering\&. 
.SH "Field Documentation"
.PP 
.SS "bool isVisible"

.PP
The component is only rendered when this is set to true\&. 
.SS "double opacity"

.PP
The opacity of an entity\&. 
.SS "double scale"

.PP
The scale of rendering\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
