.TH "RGBAColor" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBAColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <misc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.RI "red channel "
.ti -1c
.RI "int \fBg\fP"
.br
.RI "green channel 
.br
 "
.ti -1c
.RI "int \fBb\fP"
.br
.RI "blue channel "
.ti -1c
.RI "int \fBa\fP"
.br
.RI "alpha channel "
.in -1c
.SH "Detailed Description"
.PP 
RGB color values with an alpha channel\&. 
.SH "Field Documentation"
.PP 
.SS "int a"

.PP
alpha channel 
.SS "int b"

.PP
blue channel 
.SS "int g"

.PP
green channel 
.br
 
.SS "int r"

.PP
red channel 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
