.TH "RGBColor" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <misc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.RI "red channel "
.ti -1c
.RI "int \fBg\fP"
.br
.RI "green channel "
.ti -1c
.RI "int \fBb\fP"
.br
.RI "blue channel "
.in -1c
.SH "Detailed Description"
.PP 
RGB color values 
.SH "Field Documentation"
.PP 
.SS "int b"

.PP
blue channel 
.SS "int g"

.PP
green channel 
.SS "int r"

.PP
red channel 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
