.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/SpriteSystems.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/SpriteSystems.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Sprite\&.h'\fP
.br
\fC#include 'Position\&.h'\fP
.br
\fC#include 'EditorSystems\&.h'\fP
.br
\fC#include 'ECS\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSprite_render\fP (\fBLayout\fP *currentLayout, \fBSprite\fP *sprite, SDL_Renderer *renderer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Sprite_render (\fBLayout\fP * currentLayout, \fBSprite\fP * sprite, SDL_Renderer * renderer)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
