.TH "Sprite" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "\fBTilemap\fP * \fBtilemap\fP"
.br
.ti -1c
.RI "\fBVec2Int\fP \fBtilePosition\fP"
.br
.ti -1c
.RI "\fBRenderProperties\fP \fBrenderProps\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ENTITY_ID"

.SS "\fBRenderProperties\fP renderProps"

.SS "\fBTilemap\fP* tilemap"

.SS "\fBVec2Int\fP tilePosition"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
