.TH "Text" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Text\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBENTITY_ID\fP"
.br
.ti -1c
.RI "char \fBvalue\fP [255]"
.br
.ti -1c
.RI "int \fBfontSize\fP"
.br
.ti -1c
.RI "char \fBfontFamily\fP [255]"
.br
.ti -1c
.RI "\fBRGBColor\fP \fBfontColor\fP"
.br
.ti -1c
.RI "\fBVec2Int\fP \fBtextBoxSize\fP"
.br
.ti -1c
.RI "\fBRenderProperties\fP \fBrenderProps\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int ENTITY_ID"

.SS "\fBRGBColor\fP fontColor"

.SS "char fontFamily[255]"

.SS "int fontSize"

.SS "\fBRenderProperties\fP renderProps"

.SS "\fBVec2Int\fP textBoxSize"

.SS "char value[255]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
