.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/TextSystems.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/TextSystems.c
.SH SYNOPSIS
.br
.PP
\fC#include 'TextSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBText_render\fP (\fBLayout\fP *currentLayout, \fBText\fP *text, SDL_Renderer *renderer, TTF_Font *ttfFont)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Text_render (\fBLayout\fP * currentLayout, \fBText\fP * text, SDL_Renderer * renderer, TTF_Font * ttfFont)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
