.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/Text.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/Text.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Text\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBText_init\fP (\fBText\fP *texts, int entityID, int *total_textComponents, char value[255], int fontSize, char fontFamily[255], \fBRGBColor\fP fontColor, \fBVec2Int\fP textBoxSize)"
.br
.ti -1c
.RI "void \fBText_delete\fP (\fBText\fP *texts, int entityID, int *total_textComponents)"
.br
.ti -1c
.RI "void \fBText_deserialise\fP (\fBText\fP *texts, int *total_textComponents, int maxNumberOfComponents, char path[255])"
.br
.ti -1c
.RI "void \fBText_serialise\fP (\fBText\fP *texts, int maxNumberOfComponents, char path[255])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Text_delete (\fBText\fP * texts, int entityID, int * total_textComponents)"

.SS "void Text_deserialise (\fBText\fP * texts, int * total_textComponents, int maxNumberOfComponents, char path[255])"

.SS "void Text_init (\fBText\fP * texts, int entityID, int * total_textComponents, char value[255], int fontSize, char fontFamily[255], \fBRGBColor\fP fontColor, \fBVec2Int\fP textBoxSize)"

.SS "void Text_serialise (\fBText\fP * texts, int maxNumberOfComponents, char path[255])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
