.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/TextSystems.h" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/TextSystems.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'SDL_ttf\&.h'\fP
.br
\fC#include 'ECS\&.h'\fP
.br
\fC#include 'Text\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBText_render\fP (\fBLayout\fP *currentLayout, \fBText\fP *text, SDL_Renderer *renderer, TTF_Font *font)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Text_render (\fBLayout\fP * currentLayout, \fBText\fP * text, SDL_Renderer * renderer, TTF_Font * font)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
