.TH "Tilemap" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tilemap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tilemap\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.RI "The texture which will be used in rendering the entities\&. "
.ti -1c
.RI "\fBVec2Int\fP \fBtileSize\fP"
.br
.RI "The dimensions of a tile\&. "
.in -1c
.SH "Detailed Description"
.PP 
Stores the texture of all entities\&. 
.SH "Field Documentation"
.PP 
.SS "SDL_Texture* texture"

.PP
The texture which will be used in rendering the entities\&. 
.SS "\fBVec2Int\fP tileSize"

.PP
The dimensions of a tile\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
