.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/Tile.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/Tile.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Tile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTile_init\fP (\fBTile\fP *tiles, int entityID, int *total_tileComponents, \fBTilemap\fP *tilemap, \fBVec2Int\fP tilePosition, \fBVec2Int\fP size)"
.br
.ti -1c
.RI "void \fBTile_delete\fP (\fBTile\fP *tiles, int entityID, int *total_tileComponents)"
.br
.ti -1c
.RI "void \fBTile_deserialise\fP (\fBTile\fP *tiles, int *total_tileComponents, int maxNumberOfComponents, char path[255], \fBTilemap\fP *tilemap)"
.br
.ti -1c
.RI "void \fBTile_serialise\fP (\fBTile\fP *tiles, int maxNumberOfComponents, char path[255])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Tile_delete (\fBTile\fP * tiles, int entityID, int * total_tileComponents)"

.SS "void Tile_deserialise (\fBTile\fP * tiles, int * total_tileComponents, int maxNumberOfComponents, char path[255], \fBTilemap\fP * tilemap)"

.SS "void Tile_init (\fBTile\fP * tiles, int entityID, int * total_tileComponents, \fBTilemap\fP * tilemap, \fBVec2Int\fP tilePosition, \fBVec2Int\fP size)"

.SS "void Tile_serialise (\fBTile\fP * tiles, int maxNumberOfComponents, char path[255])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
