.TH "D:/Projects/BME/Prog 1/_nhz/NHZ1/TileSystems.c" 3 "Sat Nov 27 2021" "Version 1.02" "Prog1_nhz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Projects/BME/Prog 1/_nhz/NHZ1/TileSystems.c
.SH SYNOPSIS
.br
.PP
\fC#include 'TileSystems\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTile_render\fP (\fBLayout\fP *currentLayout, \fBTile\fP *tile, SDL_Renderer *renderer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Tile_render (\fBLayout\fP * currentLayout, \fBTile\fP * tile, SDL_Renderer * renderer)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog1_nhz from the source code\&.
